/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int f_mpc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int f_mpc_alloc_mem(void);
int f_mpc_init_mem(int mem);
void f_mpc_free_mem(int mem);
int f_mpc_checkout(void);
void f_mpc_release(int mem);
void f_mpc_incref(void);
void f_mpc_decref(void);
casadi_int f_mpc_n_in(void);
casadi_int f_mpc_n_out(void);
casadi_real f_mpc_default_in(casadi_int i);
const char* f_mpc_name_in(casadi_int i);
const char* f_mpc_name_out(casadi_int i);
const casadi_int* f_mpc_sparsity_in(casadi_int i);
const casadi_int* f_mpc_sparsity_out(casadi_int i);
int f_mpc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int f_mpc_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define f_mpc_SZ_ARG 26
#define f_mpc_SZ_RES 24
#define f_mpc_SZ_IW 77
#define f_mpc_SZ_W 3507
#ifdef __cplusplus
} /* extern "C" */
#endif
